### ISSUE TITLE
Publish 7.0 nuget

### ISSUE THREAD

**Issue by asys-bstz** [PiranhaCMS/piranha.core.postgresql#3]
Hi, Piranha released its 7.0.0 version. As this is already updated to 7.0.0 (#2), could we get it published?

Thanks.

**Comment by junderhill** [comment]
Hi,
I am away for a week with no access to a computer. Happy to do this on my return.
J

**Comment by asys-bstz** [comment]
That's fine of course, thanks.

**Comment by wjunker** [comment]
@junderhill ping ;-)

Very nice addon, thank you :)

**Comment by junderhill** [comment]
This has now been published to NuGet. Apologies for the delay
